function [] = print_parameters(fid,teensy_fs, baseln, n_trials, prcnt_go, sig_amps, prcnt_amps,iti_len,fa_timeout_len,n_resets, play_error_sound, play_hit_sound, pulse_type, pulse_len, pulse_intrvl, sound_fs, err_freq1, err_freq2, err_amp, err_len, hit_freq1, hit_freq2, hit_amp, hit_len,tp)

%% package parameters
S = struct('Fs',teensy_fs, ...
    'racording_basline',baseln, ...
    'n_trials',n_trials,...
    'percent_go',prcnt_go,...
    'piezo_amplitudes',sig_amps,...
    'piezo_amplitude_percent',prcnt_amps,...
    'ITI_len',iti_len,...    
    'fa_timeout_length',fa_timeout_len,...
    'n_resets',n_resets,...
    'play_error_sound',play_error_sound,...
    'play_hit_sound',play_hit_sound,...
    'pizeo_shape',pulse_type,...
    'piezo_length',pulse_len,...
    'piezo_interval',pulse_intrvl,...
    'spound_fs',sound_fs,...
    'err_sound_freq1',err_freq1,...
    'err_sound_freq2',err_freq2,...
    'err_sound_amp',err_amp,...
    'err_sound_len',err_len,...
    'hit_sound_freq1',hit_freq1,...
    'hit_sound_freq2',hit_freq2,...
    'hit_sound_amp',hit_amp,...
    'hit_sound_len',hit_len);

fns = fieldnames(S);
for i = 1:numel(fns)
    fprintf(fid,['\n' fns{i} ': ' num2str(S.(fns{i}))]);
end

% also print the parameters that get senst to teensy
fns = fieldnames(tp);
for i = 1:numel(fns)
    fprintf(fid,['\n' fns{i} ': ' num2str(tp.(fns{i}))]);
end




